name: ci

on:
  push:
    branches:
      - "master"
  workflow_dispatch: # Allows manual trigger
  schedule:
    - cron: '0 0 * * 0' # Schedules the workflow to run every Sunday at midnight

env:
  HATH_VERSION_WORKFLOW: 1.6.4

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ghcr.io/izykitten/hath:latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Scan for vulnerabilities
        if: github.event_name == 'schedule'
        id: trivy-scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ghcr.io/izykitten/hath:latest
          format: 'json'
          output: 'trivy-results.json'
      - name: Upload Trivy scan results
        if: github.event_name == 'schedule'
        uses: actions/upload-artifact@v4
        with:
          name: trivy-results
          path: trivy-results.json
      - name: Check scan results
        id: check-scan
        if: github.event_name == 'schedule'
        run: |
          if grep -q "CRITICAL\|HIGH" trivy-results.json; then
            echo "Relevant CVEs found."
            exit 0
          else
            echo "No relevant CVEs found."
            exit 1
      - name: Commit changes
        if: github.event_name == 'workflow_dispatch' || github.event_name == 'push' || steps.check-scan.outcome == 'success'
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add .
          if [ "${{ github.event_name }}" = "push" ]; then
            git commit --allow-empty -m "Automated build and vulnerabilities scan"
          elif ! git diff-index --quiet HEAD; then
            git commit -m "Automated build and vulnerabilities scan"
          else
            echo "No changes to commit."
          fi
      - name: Push changes
        if: github.event_name == 'workflow_dispatch' || github.event_name == 'push' || steps.check-scan.outcome == 'success'
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.m2/repository
            ~/.npm
            ~/.cache
          key: ${{ runner.os }}-build-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-build-